CREATE TABLE Device (
    HostName VARCHAR(255) NOT NULL,
    Mac VARCHAR(255) NOT NULL,
    DUID VARCHAR(255) NOT NULL,
    IAID VARCHAR(255),
    IPv4 VARCHAR(255),
    IPv6 VARCHAR(255),
    IPv4_OutTime INT,
    IPv6_OutTime INT
);